#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'video_webm'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'webm_video.cpp',
		'webm_recorder.cpp',
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../common',
		'../../webm'
	] + bld.env.INCLUDES_SDL2

	defines = []
	bld.env.LIB = ['avutil', 'avformat', 'avcodec', 'webm', 'webm', 'vorbis', 'vorbisenc', 'vpx']
	libs = ['tier0','tier1','tier2','tier3','vstdlib', 'AVCODEC', 'AVUTIL', 'AVFORMAT']

	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	install_path = bld.env.LIBDIR

	if True:
		bld.shlib(
			source   = source,
			target   = PROJECT_NAME,
			name     = PROJECT_NAME,
			features = 'c cxx',
			includes = includes,
			defines  = defines,
			use      = libs,
			install_path = install_path,
			subsystem = bld.env.MSVC_SUBSYSTEM,
			idx      = bld.get_taskgen_count()
		)

